### ISSUE TITLE
The full code of AeroRIT

### ISSUE THREAD

**Issue by XiaoMLiu** [aneesh3108/AeroRIT#2]
Dear Aneesh,
I am very interested in your paper, AeroRIT: A New Scene for Hyperspectral Image Analysis, and would like to obtain the full version of the data set in your thesis. This is my email: xiaomeiliu95@outlook.com, I hope to hear from you soon.
Thanks
Xiaomei Liu

**Comment by aneesh3108** [comment]
Hello,
The dataset links have been available for access via email, but as of today, have been made public.

Sincere apology for not checking the issue earlier,
Thanks
